### ISSUE TITLE
Fedora 22: Digitalocean & Audit2allow unsupported locale setting

### ISSUE THREAD

**Issue by richardskumat** [richardskumat/gogsi#8]
Fedora 22 was tested on Digitalocean where wrong locale settings caused audit2allow to fail to export denied entries from /var/log/audit/audit.log and then import the module. This caused Nginx 502 errors since Selinux doesn't allow the nginx user to access the gogs web server.

The following errors were seen:

[root@f231 ~]# cat /var/log/audit/audit.log | grep nginx | grep denied | audit2allow -M nginx
Traceback (most recent call last):
  File "/usr/bin/audit2allow", line 34, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib64/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by richardskumat** [comment]
This happened on a stock Fedora 22 image.

Reminds me I need to add dnf update -y to gogs-sql.sh then.

**Comment by richardskumat** [comment]
dnf update -y on that f231 server:

Transaction Summary
=============================================================================================================================================================
Install    9 Packages
Upgrade  135 Packages

Total download size: 137 M

```
[root@f231 ~]# cat /var/log/audit/audit.log | grep nginx | grep denied | audit2allow -M nginx
******************** IMPORTANT ***********************
To make this policy package active, execute:

semodule -i nginx.pp

[root@f231 ~]# semodule -i nginx.pp

```

Seems running dnf update -y will fix this error.

**Comment by richardskumat** [comment]
It's also funny that Fedora 22 && 23 images have selinux enabled on Digitalocean.com while Centos 6 and 7 images come with selinux disabled.

**Comment by richardskumat** [comment]
Still, DO is a very good host.
